# Site settings
title: G2K Zoom Links
email: tech@gateway2khmer.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/zoom-links" # the subpath of your site, e.g. /blog/
url: "https://tech-g2k.github.io" # the base hostname & protocol for your site

# bundle exec jekyll serve --livereload

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: G2K, Gateway To Khmer.

# API settings
google_api_key:

# Build settings
markdown: kramdown

# Zoom classroom links full-time classes intake 7:
ft-l1-ln : https://zoom.us/j/91642595840?pwd=MnBMR1BLT0dVdDgzSHJjOENJRkF1Zz09
ft-l1-tx : FT-L1-i7-20
ft-l2-ln : https://zoom.us/j/96762214269?pwd=aTFwOUVrL2QyRllDSEVUVzBBWi9QQT09
ft-l2-tx : FT-L2-i7-20
ft-l3-ln : https://zoom.us/j/93278961630?pwd=cFhmUUJjNDMxVFpvYngwcnJaZGswZz09
ft-l3-tx : FT-L3-i7-20
ft-l4-ln : https://zoom.us/j/93819225004?pwd=R210OEU2SEVrUEZPS0xkVFJLN054UT09
ft-l4-tx : FT-L4-i7-20
ft-l5-ln : https://zoom.us/j/97206514653?pwd=U1lHV2ZPaXFpMzM2M09JUG54eUhFQT09
ft-l5-tx : FT-L5-i7-20
ft-l7-ln : https://zoom.us/j/92323459108?pwd=aDNQQXFsNkZRRGJKYnV2aEY2Vi9EQT09
ft-l7-tx : FT-L7-i7-20
# Zoom classroom links full-time classes intake 8:
ft-1-ln : https://zoom.us/j/95341947989?pwd=b0tMbm05K2poOXdPNm5XM0s5dVplZz09
ft-1-tx : FT-1A-i8-20
ft-2-ln : https://zoom.us/j/97046180578?pwd=RUp1eVZHTW9YRzdSV3VjZXZxbW14UT09
ft-2-tx : FT-1B-i8-20
ft-3-ln : https://zoom.us/j/99990206507?pwd=VGVIWWZ0ak5SUHplNFlVR0oyN3BKUT09
ft-3-tx : FT-2-i8-20
ft-4-ln : https://zoom.us/j/99899431067?pwd=TFdTdWhCV29Sc0VTcXFTdlpUT0pPQT09
ft-4-tx : FT-3-i8-20
ft-5-ln : https://zoom.us/j/98700367402?pwd=V09nWmRldE5BYXh5Tjc2TFBHSE80QT09
ft-5-tx : FT-4-i8-20
ft-6-ln : https://zoom.us/j/91348306661?pwd=OHFKS3ZjTjBXVTJhOExXOFRmTXhXZz09
ft-6-tx : FT-5-i8-20
ft-7-ln : https://zoom.us/j/93014712031?pwd=OS9DaFpTYWlLR0FNTEJ5NnJMb3RzZz09
ft-7-tx : FT-6-i8-20
ft-9-ln : https://zoom.us/j/94971947980?pwd=bCtiNWE2SzFIc1k5anRuTlFPdEdmdz09
ft-9-tx : FT-8-i8-20

# Zoom classroom links Christian Study
ks-i7-ln : https://zoom.us/j/97337701712?pwd=cmozQk1hQXZ6TDlpZFNMWVhzVzcrQT09
ks-i7-tx : KS-i7-20

# Zoom classroom links part-time
pt-l1-ln : https://zoom.us/j/94293732336?pwd=TjlWczBhMEFmUHQydHR3aFQ5TjJDZz09
pt-l1-tx : PT-L1-i7-20
pt-l2-ln : https://zoom.us/j/91039885020?pwd=ZnhOOUtoVXA4ck5LZkU4b2NQY2U2Zz09
pt-l2-tx : PT-L2A-i7-20
pt-l2b-ln : https://zoom.us/j/95304008450?pwd=dFFCVmQ3M21oOVVMeGxSQmJ2a0Rjdz09
pt-l2b-tx : PT-L2B-i7-20
pt-l3-ln : https://zoom.us/j/97091736988?pwd=clh2K210S2R1clNoWnFueTdXM0psZz09
pt-l3-tx : PT-L3-i7-20
pt-l4-ln : https://zoom.us/j/92533270646?pwd=VFh3WGgzL2k0U2xnOVNGOFFvbnB3QT09
pt-l4-tx : PT-L4A-i7-20
pt-l4b-ln : https://zoom.us/j/98936168237?pwd=d1dtMlhaNkFwNkNwcE9KaXlGMm1qdz09
pt-l4b-tx : PT-L4B-i7-20
pt-l5-ln : https://zoom.us/j/96867384133?pwd=U2ZyT3RzVDVwY1c2Y2cxMEs0MXdtZz09
pt-l5-tx : PT-L5-i7-20
pt-l6-ln : https://zoom.us/j/93708857949?pwd=ZVhnZERnSURqZitqd1prTlAxWFdsZz09
pt-l6-tx : PT-L6-i7-20
pt-l7-ln : https://zoom.us/j/98683220993?pwd=MjB0ZW11dWZIQ2U3UzU4bzgxb3NhZz09
pt-l7-tx : PT-L7A-i7-20
pt-l7b-ln : https://zoom.us/j/99158834609?pwd=dzhJQlpVdjc0ZjlTRVI5QUJLYVhSdz09
pt-l7b-tx : PT-L7B-i7-20

# Zoom classroom links evening classes
ev-l1-ln : https://zoom.us/j/96040626098?pwd=ZUg3YmVyVW8yRzdDRVRLSnR1Y1JRUT09
ev-l1-tx : EV-L1A-i7-20
ev-l1b-ln : https://zoom.us/j/95014761737?pwd=aHBGNUhSSm1UMmgzbDdneThKeldPdz09
ev-l1b-tx : EV-L1B-i7-20
ev-l2-ln : https://zoom.us/j/96375421714?pwd=S1FOaVROazM1N1hlNVFXVUk3Zjc5QT09
ev-l2-tx : EV-L2A-i7-20
ev-l2b-ln : 
ev-l2b-tx : EV-L2B-i7-20
ev-l3-ln : https://zoom.us/j/95147812631?pwd=cXdFNThHcVJaNk1UYkNuMGtYVUU3dz09
ev-l3-tx : EV-L3-i7-20
ev-l4-ln : https://zoom.us/j/93905012219?pwd=MmdSUzBPWFpwbFRKNk1PZWpzei9MUT09
ev-l4-tx : EV-L4-i7-20
ev-hc-ln : https://zoom.us/j/95976103560?pwd=T0syYmYzcU1saFhOQ25HbFdKbWtFZz09
ev-hc-tx : EV-HC-i7-20

# Zoom links for i1, 2021
ft-l1-ln : https://zoom.us/j/99634070477?pwd=YnlCczBEakNQWDMyWUxYcG9VQWl2Zz09
ft-l1-tx : FT-L1-i1-21
ft-l2-ln : https://zoom.us/j/96123078467?pwd=WWtDUGVCT0phQS9FVHBMTzl1cXpKdz09
ft-l2-tx : FT-L2-i1-21
ft-l4-ln : https://zoom.us/j/93239738817?pwd=cWlINklURkM1bWlwRzVDRWIxMUlVZz09
ft-l4-tx : FT-L4-i1-21
ft-l5-ln : https://zoom.us/j/94476828022?pwd=VmtpVmlybnJMNU85aHJidTFHWUdRUT09
ft-l5-tx : FT-L5-i1-21
ft-l7-ln : https://zoom.us/j/91530294983?pwd=dG9JaGVvQUtSM2dVaGp4aWNUQ3Vodz09
ft-l7-tx : FT-L7-i1-21
ft-i8-ln : https://zoom.us/j/99465833286?pwd=WTgyTjlpbUpJUXZzUS9pQnJMRTNldz09
ft-i8-tx : FT-L8-i1-21

pt-l1-ln : https://zoom.us/j/94338591298?pwd=R3ZEbmRKWDBqbEFWeUVjUkU4SUFzZz09
pt-l1-tx : PT-L1-i1-21
pt-l2-ln : https://zoom.us/j/98511768477?pwd=VlZUcktXcFVkMHlyUlBZSkUvQWphdz09
pt-l2-tx : PT-L2-i1-21
pt-l4-ln : https://zoom.us/j/98218273190?pwd=STZLbklFQVRzZ3hNWHEvdXRnR25Hdz09
pt-l4-tx : PT-L4-i1-21
pt-l5-ln : https://zoom.us/j/95355255971?pwd=YmhzdzJvUmFobC9mWHF1VXVxajUvUT09
pt-l5-tx : PT-L5-i1-21
pt-l7-ln : https://zoom.us/j/99184303257?pwd=R05qaFU0cDFVK3pnVWFkUVpKdTIvZz09
pt-l7-tx : PT-L7-i1-21
pt-l8-ln : https://zoom.us/j/93580956483?pwd=bWE3UFd3SlJRY25RZGg4eit5Z0dzQT09
pt-l8-tx : PT-L8-i1-21
pt-l9-ln : https://zoom.us/j/96480984716?pwd=Q1BRMy95QkZpcHVFRlBUZkR4T0FoZz09
pt-l9-tx : PT-L9-i1-21
pt-l10-ln : https://zoom.us/j/97824538316?pwd=ejRMblN3SnNoOEtmTDl0a1NjN1BqQT09
pt-l10-tx : PT-L10-i1-21

ev-l1-ln : https://zoom.us/j/97695366948?pwd=RUxFQm16d1NDczBObzVBZDRnVURodz09
ev-l1-tx : EV-L1A-i1-21
ev-l1b-ln : https://zoom.us/j/93997240755?pwd=cy9FWFF0L2MrRTRGWVJ3ekFnMUo3QT09
ev-l1b-tx : EV-L1B-i1-21
ev-l2-ln : https://zoom.us/j/98514896579?pwd=a21XZERJMzltR29YQTFUcmdXVVFWQT09
ev-l2-tx : EV-L2-i1-21
ev-l4-ln : https://zoom.us/j/93769465983?pwd=S1dDQlVKZlFNNzVHejg3a3paOFpNdz09
ev-l4-tx : EV-L4-i1-21
ev-l5-ln : https://zoom.us/j/99284175168?pwd=YzVvaUF5Nnp4U3l5bUZvdFRwbkVQZz09
ev-l5-tx : EV-L5-i1-21
