# Site settings
title: G2K Zoom Links
email: tech@gateway2khmer.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/zoom-links" # the subpath of your site, e.g. /blog/
url: "https://tech-g2k.github.io" # the base hostname & protocol for your site

# bundle exec jekyll serve --livereload

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: G2K, Gateway To Khmer.

# API settings
google_api_key:

# Build settings
markdown: kramdown

# Zoom links for i1 & i2, 2021
ft-l1-ln : https://zoom.us/j/96821178066?pwd=ZzFyNE12VVA5V1dTTHBra1h3VHNnZz09
ft-l1-tx : FT-L1-i2-21
ft-l2-ln : https://zoom.us/j/93895029355?pwd=b3pqRFYzQ2tPd2Z2M1c3MmpwaWc1QT09
ft-l2-tx : FT-L2-i2-21
ft-l3-ln : https://zoom.us/j/98801723901?pwd=d0U4WHczejQxMEZzbkJQcGlZQmdJZz09
ft-l3-tx : FT-L3-i2-21
ft-l5-ln : https://zoom.us/j/99964102700?pwd=TVBqSDZLeFFNenJybHBXeFk5QlBUdz09
ft-l5-tx : FT-L5-i2-21
ft-l6-ln : https://zoom.us/j/91548903667?pwd=ZzFWOEpmVzMzOWUzZXNaeFc5d085dz09
ft-l1-tx : FT-L6-i2-21
ft-i8-ln : https://zoom.us/j/98148588093?pwd=U3Z6VlNsTnUxOXd1RVJIR2tCN3hHQT09
ft-i8-tx : FT-L8-i2-21
ft-l9-ln : https://zoom.us/j/99649083151?pwd=a21XZERJMzltR29YQTFUcmdXVVFWQT09
ft-l9-tx : FT-L9-i2-21

pt-l1-ln : https://zoom.us/j/94338591298?pwd=R3ZEbmRKWDBqbEFWeUVjUkU4SUFzZz09
pt-l1-tx : PT-L1-i1-21
pt-l2-ln : https://zoom.us/j/98511768477?pwd=VlZUcktXcFVkMHlyUlBZSkUvQWphdz09
pt-l2-tx : PT-L2-i1-21
pt-l4-ln : https://zoom.us/j/98218273190?pwd=STZLbklFQVRzZ3hNWHEvdXRnR25Hdz09
pt-l4-tx : PT-L4-i1-21
pt-l5-ln : https://zoom.us/j/95355255971?pwd=YmhzdzJvUmFobC9mWHF1VXVxajUvUT09
pt-l5-tx : PT-L5-i1-21
pt-l7-ln : https://zoom.us/j/99184303257?pwd=R05qaFU0cDFVK3pnVWFkUVpKdTIvZz09
pt-l7-tx : PT-L7-i1-21
pt-l8-ln : https://zoom.us/j/93580956483?pwd=bWE3UFd3SlJRY25RZGg4eit5Z0dzQT09
pt-l8-tx : PT-L8-i1-21
pt-l9-ln : https://zoom.us/j/96480984716?pwd=Q1BRMy95QkZpcHVFRlBUZkR4T0FoZz09
pt-l9-tx : PT-L9-i1-21
pt-l10-ln : https://zoom.us/j/97824538316?pwd=ejRMblN3SnNoOEtmTDl0a1NjN1BqQT09
pt-l10-tx : PT-L10-i1-21

ev-l1-ln : https://zoom.us/j/97695366948?pwd=RUxFQm16d1NDczBObzVBZDRnVURodz09
ev-l1-tx : EV-L1A-i1-21
ev-l1b-ln : https://zoom.us/j/93997240755?pwd=cy9FWFF0L2MrRTRGWVJ3ekFnMUo3QT09
ev-l1b-tx : EV-L1B-i1-21
ev-l2-ln : https://zoom.us/j/98514896579?pwd=a21XZERJMzltR29YQTFUcmdXVVFWQT09
ev-l2-tx : EV-L2-i1-21
ev-l4-ln : https://zoom.us/j/93769465983?pwd=S1dDQlVKZlFNNzVHejg3a3paOFpNdz09
ev-l4-tx : EV-L4-i1-21
ev-l5-ln : https://zoom.us/j/99284175168?pwd=YzVvaUF5Nnp4U3l5bUZvdFRwbkVQZz09
ev-l5-tx : EV-L5-i1-21
