# Site settings
title: G2K Zoom Links
email: tech@gateway2khmer.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/zoom-links" # the subpath of your site, e.g. /blog/
url: "https://tech-g2k.github.io" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: G2K, Gateway2Khmer.

# API settings
google_api_key:

# Build settings
markdown: kramdown

# Zoom classroom links full-time classes
ft-1a-text : FT-1A-i6-20
ft-1a-link : https://zoom.us/j/94436208202?pwd=ZXZUWm0yQ2E1bHFJOUxXV3V6a01QUT09
ft-1b-text : FT-1B-i6-20
ft-1b-link : https://zoom.us/j/94334894369?pwd=WFA5ZXNHQ0c4eWpFUVlkTm5jS1d1Zz09
ft-2-text : FT-2-i6-20
ft-2-link : https://zoom.us/j/95037173417?pwd=SDlaMHl4MXFQY2RqS0VyazUrZnZvUT09
ft-3-text : FT-3-i6-20
ft-3-link : https://zoom.us/j/96881517728?pwd=b2lGeHlkaVBiSGYxWmljV2gvQkJkQT09
ft-4-text : FT-4-i6-20
ft-4-link : https://zoom.us/j/97401212748?pwd=SDFicGtid2JqYk1peTZPU1JITGdNQT09
ft-5-text : FT-5-i6-20
ft-5-link : https://zoom.us/j/93849409606?pwd=Mm84U3hYdlNCMzIwS3J4QmlxcUVDZz09
ft-6-text : FT-6-i6-20
ft-6-link : https://zoom.us/j/91524566636?pwd=ejlEanhNNmhWb3VrTUlQYjZ2cVBnZz09
ft-7-text : FT-7-i6-20
ft-7-link : https://zoom.us/j/96096545224?pwd=c2xSN0k3cXN5MEV4SmtDNDBLUjNrQT09

# Zoom classroom links Christian Study
cs-2-text : CS-2-i6-20
cs-2-link : 
ks-text : KS-i6-20
ks-link : 

# Zoom classroom links part-time
PTL1A-i5-20 : https://zoom.us/j/92807329082?pwd=b0JqSkRiUUNEb09hL0pBYWtyc3Zvdz09
PTL1B-i5-20 : https://zoom.us/j/97408945927?pwd=ZDVVVHpPSElCNGZkWWdvNkVUVkpTdz09
PTL2A-i5-20 : https://zoom.us/j/94058653262?pwd=eFJrc0RETnBGaFZNM1ZiZ3kwUUJNZz09
PTL3A-i5-20 : https://zoom.us/j/98723341445?pwd=WjZEdmlES0NmTkVmbUU1Z1ZzcngwZz09
PTL3B-i5-20 : https://zoom.us/j/93885876511?pwd=VG5vMElzUmZMeU1rTWJadHBBd2tjZz09
PTL4A-i5-20 : https://zoom.us/j/95546095321?pwd=bXppVTlaVDFiN2lDa0xOUWI0dG8zQT09
PTL6A-i5-20 : https://zoom.us/j/93087125021?pwd=UTJhL0tjY1cyYitLdVRLaVJjd2Y2dz09

# Zoom classroom links evening classes
EVL1A-i5-20 : https://zoom.us/j/94359249790?pwd=SUQxeFFCaW1XSzFkZmx1R0JJQmNiQT09
EVL1B-i5-20 : https://zoom.us/j/94340526806?pwd=ZFFWdWh4bkhLUXhGMDVrSjRRcGdFUT09
EVL2A-i5-20 : https://zoom.us/j/91661136396?pwd=Tm9HV0F3TUUxMS9pL2tzTWlMa014QT09
EVL2B-i5-20 : https://zoom.us/j/99919118079?pwd=S1MyVmRsbXp2N3NCWm9hQWZqVFhKdz09
EVL3A-i5-20 : https://zoom.us/j/96862704694?pwd=UkRwd3lXeVVUQ1N6b0FxYmE1U2Z2Zz09
EVL4A-i5-20 : https://zoom.us/j/91740153461?pwd=OUpwV09KT21RTElxVDNkZXpSMlIxZz09

