# Site settings
title: G2K Zoom Links
email: tech@gateway2khmer.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zoom.gateway2khmer.com" # the base hostname & protocol for your site

# bundle exec jekyll serve --livereload

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: G2K, Gateway To Khmer.

# API settings
google_api_key:

# Build settings
markdown: kramdown

# Zoom placement test link
placement-link : https://zoom.us/j/96583080845
placement-text : Placement

