# Site settings
title: G2K Zoom Links
email: tech@gateway2khmer.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/zoom-links" # the subpath of your site, e.g. /blog/
url: "https://tech-g2k.github.io" # the base hostname & protocol for your site

# bundle exec jekyll serve --livereload

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: G2K, Gateway To Khmer.

# API settings
google_api_key:

# Build settings
markdown: kramdown

# Zoom links for i3 & i4, 2021
ft-text1 : FT-L1-i3-21
ft-text3 : FT-L3-i3-21
ft-text4 : FT-L4-i3-21
ft-text5 : FT-L5-i3-21
ft-text6 : FT-L6-i3-21
ft-text7 : FT-L7-i3-21
ft-text10 : FT-L10-i3-21
ft-link1 : https://zoom.us/j/96233684908?pwd=OUJKWmZCYk1BbjVnV2RHVG1PSExSQT09
ft-link3 : https://zoom.us/j/92881785740?pwd=RGdpczR3amlBc3EvQjYzK1g1cWhLUT09
ft-link4 : https://zoom.us/j/93015353108?pwd=TUNsN2RNWktFK3c1bkYyV2tmNU91QT09
ft-link5 : https://zoom.us/j/96327435455?pwd=T25nSWZQWEJraVMvRFNrbU1mQUVpdz09
ft-link6 : https://zoom.us/j/99378246099?pwd=R2tWQnBWQXVyZVA1dkh4YkhYOVN5UT09
ft-link7 : https://zoom.us/j/96436654628?pwd=M2cvRlI1Q1Z6QndOTHZpTHpHYkRmUT09
ft-link10 : https://zoom.us/j/92027610354?pwd=SmpzOFZJdlF2enc1djRJRXBtUHBxUT09

pt-text1 : PT-L1-i3-21
pt-text2 : PT-L2-i3-21
pt-text3 : PT-L3-i3-21
pt-text5 : PT-L5-i3-21
pt-text6 : PT-L6-i3-21
pt-text8 : PT-L8-i3-21
pt-text9 : PT-L9-i3-21
pt-text10 : PT-L10-i3-21
pt-link1 : https://zoom.us/j/99240205157?pwd=ZEsrcWNYUVZ0SU1KRHRadjdvRU8zUT09
pt-link2 : https://zoom.us/j/92856648038?pwd=L3NsNVRpOXpqcS8rWTkwZVNiSS9Kdz09
pt-link3 : https://zoom.us/j/93942590800?pwd=STZLbklFQVRzZ3hNWHEvdXRnR25Hdz09
pt-link5 : https://zoom.us/j/94921484481?pwd=ZXR4SjhLT3RUa2IwVW0yY2JZUUZOZz09
pt-link6 : https://zoom.us/j/93903864067?pwd=UHFjZC9QRDE4WmtiV3hxQ1JkZW5ZQT09
pt-link8 : https://zoom.us/j/98579368709?pwd=dTl0NkNoMmNLbkpCQkZFLzZlQllRdz09
pt-link9 : https://zoom.us/j/96507212302?pwd=NlJTb1NxSlVGNzJneExESCtmckszdz09
pt-link10 : https://zoom.us/j/91530390258?pwd=YWhzS2tZbWdQa2dXdDN5d21aUnU4Zz09

ev-text1 : EV-L1A-i3-21
ev-text1b : EV-L1B-i3-21
ev-text2 : EV-L2-i3-21
ev-text3 : EV-L3-i3-21
ev-text5 : EV-L5-i3-21
ev-link1 : https://zoom.us/j/91299370386?pwd=US81ajlWNUs0aDg3cHVHNUMxRFJyZz09
ev-link1b : https://zoom.us/j/93630712385?pwd=VlZUcktXcFVkMHlyUlBZSkUvQWphdz09
ev-link2 : https://zoom.us/j/97415045442?pwd=RmhkSnFoaTZQdUxnWUUyUE9zbGZ3Zz09
ev-link3 : https://zoom.us/j/96308914120?pwd=MlZvM1V4Rm03eVVFak0zUk5XaVZWdz09
ev-link5 : https://zoom.us/j/91466805602?pwd=aUIwZlZzUXd3STlXVHVtVm40REh0dz09

